### ISSUE TITLE
Start Tracking Functionality

### ISSUE THREAD

**Issue by Tavernari** [Tavernari/SwiftCuckoo#3]
**Description:** Implement functionality for starting time tracking of a task.
- **Goals:**
  - Create a function to start tracking that takes task ID as input.
  - Store the start time when tracking is initialized.

**Comment by dhargrow** [comment]
Since session start and end times won't be constant, any thoughts on using Session as a inout parameter? That way we can persist changes when storing start time. Just a thought, let me know what you think. @Tavernari
